[package]
name = "bevy-discord-presence"
description = "Discord presence plugin for the Bevy game engine"
license = "MIT"
authors = ["Juliette Cordor"]
keywords = ["discord", "rpc", "ipc"]
version = "0.3.2"
repository  = "https://github.com/jewlexx/discord-presence.git"
edition = "2021"

[dependencies]
discord-presence = { version = "0.5", git = "https://github.com/jewlexx/discord-presence" }
bevy = { version = "0.7", default-features = false, git = "https://github.com/bevyengine/bevy", tag = "v0.7.0" }
parking_lot = "0.12"

[dev-dependencies]
version-sync = "0.9"
